config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'

  resources :messages, except: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  SLUG_REGEX = /\A[a-z-]+[a-z]+\z/

  validates :name,
    format: {
      with: SLUG_REGEX,
      message: 'can only contain lowercase letters and dashes'
    },
    length: { maximum: 25 },
    presence: true,
    uniqueness: true
  validates :spec,
    length: { maximum: 250 },
    presence: true

  def output
    Message::SpecRunner.new(spec).run
  end
end

app/models/message/spec_runner.rb
class Message::SpecRunner
  DISPLAY_CODE_REGEX = /(\$\${[^}]*\})/ # e.g. $${foo}
  INTERPOLATION_REGEX = /((?<!\$)\${[^}]*\})/ # e.g. ${foo}

  def initialize(string)
    self.string = string
  end

  def run
    # Disassemble the string
    array_of_substrings.map do |substring|
      if interpolate_code?(substring)
        recursively_interpolate(substring) # Interpolate if necessary
      elsif display_code?(substring)
        present_as_code(substring) # Leave code samples as-is
      else
        substring # Otherwise, leave alone
      end
    end.join()
    # Re-assemble the string
  end

  private

  attr_accessor :string

  def array_of_substrings
    # Create an array with two types of substrings:
    # 1. interpolatable values
    # 2. everything else
    string.split(INTERPOLATION_REGEX)
  end

  def display_code?(substring)
    # e.g. "$${no-interpolation}"
    substring.match(DISPLAY_CODE_REGEX)
  end

  def find_message_spec_by(substring)
    # Return the spec of Message in DB with matching name, or nil if none exists
    Message.find_by_name(substring).try(:spec)
  end

  def interpolate_code?(substring)
    # e.g. "${interpolation}"
    substring.match(INTERPOLATION_REGEX)
  end

  def message_name(substring)
    # Return the value in between `${` and `}`
    substring[2..-2]
  end

  def present_as_code(substring)
    # Remove the first dollar sign
    substring.gsub('$$', '$')
  end

  def recursively_interpolate(substring)
    spec = find_message_spec_by(message_name(substring))

    # If spec exists in db, return its output and the output of all referenced specs, infinitely.
    # Otherwise return substring as-is.
    spec ? Message::SpecRunner.new(spec).run : substring
  end
end

app/models/string_interpolator.rb
class StringInterpolator
  INTERPOLATION_REGEX = /((?<!\$)\${[^}]*\})/ # e.g. ${foo}
  DISPLAY_CODE_REGEX = /(\$\${[^}]*\})/ # e.g. $${foo}

  attr_accessor :string

  def initialize(string)
    self.string = string
  end

  def interpolate
    array_of_substrings.map do |str|
      if interpolate?(str)
        re_interpolate(str)
      elsif display_code?(str)
        str.gsub('$$', '$')
      else
        str
      end
    end.join()
  end

  private

  def array_of_substrings
    # Create an array with two types of substrings:
    # 1. interpolatable values, e.g. "${message-name}"
    # 2. everything else, e.g. "random text" or "$${no-interpolation}"
    string.split(INTERPOLATION_REGEX)
  end

  def display_code?(str)
    str.match(DISPLAY_CODE_REGEX)
  end

  def find_message_spec_by(str)
    Message.find_by_name(str).try(:spec)
  end

  def interpolate?(str)
    str.match(INTERPOLATION_REGEX)
  end

  def message_name(str)
    # Return the value in between `${` and `}`
    str[2..-2]
  end

  def re_interpolate(str)
    value = find_message_spec_by(message_name(str))

    value ? StringInterpolator.new(value).interpolate : str
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    message = Message.find_by_id(params[:message_id])

    if message
      flash.now[:notice] = message.output
    end

    @messages = Message.all.order(:name)
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path(message_id: @message.id) }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to messages_path(message_id: @message.id) }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:name, :spec)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(key)
    {
      alert: 'is-danger',
      info: 'is-info',
      notice: 'is-success',
      warning: 'is-warning'
    }[key.to_sym]
  end

  def form_field_classes(attr_key, message, classes, validation_key = nil)
    field_has_errors = message.errors.messages[attr_key].present?

    if field_has_errors
      error_key = message.errors.details[attr_key][0][:error]
      validation_is_applicable = (validation_key == error_key)

      classes += ' is-danger' if (validation_is_applicable || validation_key.nil?)
    end

    classes
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interpol8r</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" sizes="32x32" href="https://andrewborstein.github.io/portfolio/static/img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="https://andrewborstein.github.io/portfolio/static/img/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="https://andrewborstein.github.io/portfolio/static/img/favicon/favicon-16x16.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-link" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to 'Interpol8r', root_path, class: 'navbar-item has-text-weight-semibold is-uppercase', style: 'letter-spacing: 3px' %>
        <a role="button" class="navbar-burger has-text-white" data-burger aria-label="menu" aria-expanded="false">
          <span aria-hidden="true" style="pointer-events: none"></span>
          <span aria-hidden="true" style="pointer-events: none"></span>
          <span aria-hidden="true" style="pointer-events: none"></span>
        </a>
      </div>
      <div class="navbar-menu" data-nav>
        <div class="navbar-end">
          <%= link_to 'Message List', messages_path, class: 'navbar-item is-uppercase is-default' %>
          <%= link_to 'New Message', new_message_path, class: 'navbar-item is-uppercase' %>
        </div>
      </div>
    </nav>

    <div class="container">
      <% flash.each do |name, msg| %>
        <section class="section" style="padding-bottom: 0" data-dismiss-target>
          <article class="message <%= flash_class(name) %>" role="alert">
            <div class="message-body is-flex level">
              <strong><%= msg %></strong>
              <button class="delete" aria-label="delete" data-dismiss></button>
            </div>
          </article>
        </section>
      <% end %>

      <section class="section">
        <%= yield %>
      </section>
    </div>

    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <div class="field">
    <%= form.label :name, class: 'label' do %>
      Name <span class="has-text-grey has-text-weight-normal">(required)<span>
    <% end %>
    <div class="control">
      <%= form.text_field :name, class: form_field_classes(:name, message, 'input') %>
    </div>
    <p class="<%= form_field_classes(:name, message, 'help', :too_long) %>">
      Must be 25 characters or less.
    </p>
    <p class="<%= form_field_classes(:name, message, 'help', :invalid) %>">
      Must contain only lowercase letters or dashes e.g. <code>message-name</code>.
    </p>
  </div>

  <div class="field">
    <%= form.label :spec, class: 'label' do %>
      Spec <span class="has-text-grey has-text-weight-normal">(required)</span>
    <% end %>
    <div class="control">
      <%= form.text_area :spec, class: form_field_classes(:spec, message, 'textarea') %>
    </div>
    <p class="<%= form_field_classes(:spec, message, 'help', :too_long) %>">
      Must be 250 characters or less.
    </p>
    <p class="help">
      To embed the output of another Message, enter its Name e.g. <code>${name}</code>.
    </p>
    <p class="help">
      To display embed code as plain text, use two dollar signs e.g. <code>$${name}</code>.
    </p>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <%= form.submit 'Submit', class: 'button is-primary has-text-weight-semibold is-uppercase' %>
    </div>
    <div class="control">
      <%= link_to 'Cancel', messages_path, class: 'button is-text' %>
    </div>
  </div>
<% end %>

app/views/messages/edit.html.erb
<div class="columns is-centered">
  <div class="column is-two-thirds">
    <h1 class='title'>Edit Message</h1>
    <%= render 'form', message: @message %>
  </div>
</div>

app/views/messages/index.html.erb
<h1 class="title">Messages</h1>

<% @messages.in_groups_of(2) do |messages| %>
  <div class="columns">
    <% messages.each do |message| %>
      <div class="column is-one-half">
        <% if message.present? %>
          <div class="card">
            <header class="card-header" style="position: relative; z-index: 1">
              <p class="card-header-title">
                <%= message.name %>
              </p>
              <%= link_to edit_message_path(message), class: 'card-header-icon has-text-grey' do %>
                <span class="icon" aria-label="Edit message" title="Edit Message">
                  <i class="fas fa-edit" aria-hidden="true"></i>
                </span>
              <% end %>
              <%= link_to message, class: 'card-header-icon has-text-grey', method: :delete, data: { confirm: 'Are you sure?' } do %>
                <span class="icon" aria-label="Delete message" title="Delete Message">
                  <i class="fas fa-trash" aria-hidden="true"></i>
                </span>
              <% end %>
            </header>
            <div class="card-content is-paddingless">
              <div class="content">
                <pre><%= message.spec %></pre>
              </div>
            </div>
            <footer class="card-footer">
              <%= link_to 'RUN', messages_path(message_id: message.id), class: 'card-footer-item has-text-weight-semibold' %>
            </footer>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/messages/new.html.erb
<div class="columns is-centered">
  <div class="column is-two-thirds">
    <h1 class='title'>New Message</h1>
    <%= render 'form', message: @message %>
  </div>
</div>